export const quickInsertTemplates = [
    { label: "Fraction", latex: "\\frac{a}{b}" },
    { label: "Exponent", latex: "x^{n}" },
    { label: "Subscript", latex: "x_{i}" },
    { label: "Square Root", latex: "\\sqrt{x}" },
    { label: "Greek Pi", latex: "\\pi" },
    { label: "Infinity", latex: "\\infty" },
    { label: "Sum", latex: "\\sum_{i=1}^{n}" },
    { label: "Integral", latex: "\\int_{a}^{b}" }
];

export const formulaLibrary: any = {
    basic: {
        title: "Basic Syntax",
        formulas: [
            { name: "Fraction", latex: "\\frac{a}{b}" },
            { name: "Mixed Fraction", latex: "a\\frac{b}{c}" },
            { name: "Exponent (Superscript)", latex: "x^2" },
            { name: "Complex Exponent", latex: "x^{10}" },
            { name: "Negative Exponent", latex: "x^{-1}" },
            { name: "Subscript", latex: "x_1" },
            { name: "Complex Subscript", latex: "x_{10}" },
            { name: "Both Super & Sub", latex: "x_i^2" },
            { name: "Square Root", latex: "\\sqrt{x}" },
            { name: "Cube Root", latex: "\\sqrt[3]{x}" },
            { name: "Nth Root", latex: "\\sqrt[n]{x}" },
            { name: "Parentheses", latex: "\\left( \\frac{a}{b} \\right)" },
            { name: "Brackets", latex: "\\left[ x \\right]" },
            { name: "Curly Braces", latex: "\\left\\{ x \\right\\}" },
            { name: "Angle Brackets", latex: "\\langle x \\rangle" },
            { name: "Absolute Value", latex: "\\left| x \\right|" },
            { name: "Norm", latex: "\\left\\| x \\right\\|" },
            { name: "Floor Function", latex: "\\lfloor x \\rfloor" },
            { name: "Ceiling Function", latex: "\\lceil x \\rceil" },
            { name: "Overline", latex: "\\overline{AB}" },
            { name: "Underline", latex: "\\underline{AB}" },
            { name: "Vector", latex: "\\vec{v}" },
            { name: "Bold Vector", latex: "\\mathbf{v}" },
            { name: "Hat", latex: "\\hat{i}" },
            { name: "Tilde", latex: "\\tilde{x}" },
            { name: "Bar", latex: "\\bar{x}" },
            { name: "Dot", latex: "\\dot{x}" },
            { name: "Double Dot", latex: "\\ddot{x}" },
            { name: "Text in Formula", latex: "x \\text{ and } y" },
            { name: "Bold Text", latex: "\\textbf{bold}" },
            { name: "Italic", latex: "\\textit{italic}" },
            { name: "Space", latex: "a \\quad b" },
            { name: "Small Space", latex: "a \\, b" },
            { name: "Prime", latex: "f'(x)" },
            { name: "Double Prime", latex: "f''(x)" },
            { name: "Degree Symbol", latex: "90^\\circ" },
            { name: "Percentage", latex: "50\\%" },
            { name: "Factorial", latex: "n!" },
            { name: "Binomial Coefficient", latex: "\\binom{n}{k}" }
        ]
    },
    symbols: {
        title: "Symbols",
        sections: [
            {
                name: "Greek Letters (Lowercase)",
                formulas: [
                    { name: "Alpha", latex: "\\alpha" },
                    { name: "Beta", latex: "\\beta" },
                    { name: "Gamma", latex: "\\gamma" },
                    { name: "Delta", latex: "\\delta" },
                    { name: "Epsilon", latex: "\\epsilon" },
                    { name: "Varepsilon", latex: "\\varepsilon" },
                    { name: "Zeta", latex: "\\zeta" },
                    { name: "Eta", latex: "\\eta" },
                    { name: "Theta", latex: "\\theta" },
                    { name: "Vartheta", latex: "\\vartheta" },
                    { name: "Iota", latex: "\\iota" },
                    { name: "Kappa", latex: "\\kappa" },
                    { name: "Lambda", latex: "\\lambda" },
                    { name: "Mu", latex: "\\mu" },
                    { name: "Nu", latex: "\\nu" },
                    { name: "Xi", latex: "\\xi" },
                    { name: "Pi", latex: "\\pi" },
                    { name: "Rho", latex: "\\rho" },
                    { name: "Sigma", latex: "\\sigma" },
                    { name: "Tau", latex: "\\tau" },
                    { name: "Upsilon", latex: "\\upsilon" },
                    { name: "Phi", latex: "\\phi" },
                    { name: "Varphi", latex: "\\varphi" },
                    { name: "Chi", latex: "\\chi" },
                    { name: "Psi", latex: "\\psi" },
                    { name: "Omega", latex: "\\omega" }
                ]
            },
            {
                name: "Greek Letters (Uppercase)",
                formulas: [
                    { name: "Gamma", latex: "\\Gamma" },
                    { name: "Delta", latex: "\\Delta" },
                    { name: "Theta", latex: "\\Theta" },
                    { name: "Lambda", latex: "\\Lambda" },
                    { name: "Xi", latex: "\\Xi" },
                    { name: "Pi", latex: "\\Pi" },
                    { name: "Sigma", latex: "\\Sigma" },
                    { name: "Upsilon", latex: "\\Upsilon" },
                    { name: "Phi", latex: "\\Phi" },
                    { name: "Psi", latex: "\\Psi" },
                    { name: "Omega", latex: "\\Omega" }
                ]
            },
            {
                name: "Operators & Relations",
                formulas: [
                    { name: "Plus", latex: "+" },
                    { name: "Minus", latex: "-" },
                    { name: "Plus/Minus", latex: "\\pm" },
                    { name: "Minus/Plus", latex: "\\mp" },
                    { name: "Times", latex: "\\times" },
                    { name: "Division", latex: "\\div" },
                    { name: "Dot Product", latex: "\\cdot" },
                    { name: "Asterisk", latex: "\\ast" },
                    { name: "Star", latex: "\\star" },
                    { name: "Circle", latex: "\\circ" },
                    { name: "Bullet", latex: "\\bullet" },
                    { name: "Equals", latex: "=" },
                    { name: "Not Equal", latex: "\\neq" },
                    { name: "Approximately", latex: "\\approx" },
                    { name: "Almost Equal", latex: "\\simeq" },
                    { name: "Congruent", latex: "\\cong" },
                    { name: "Equivalent", latex: "\\equiv" },
                    { name: "Proportional", latex: "\\propto" },
                    { name: "Similar", latex: "\\sim" },
                    { name: "Less Than", latex: "<" },
                    { name: "Greater Than", latex: ">" },
                    { name: "Less or Equal", latex: "\\leq" },
                    { name: "Greater or Equal", latex: "\\geq" },
                    { name: "Much Less", latex: "\\ll" },
                    { name: "Much Greater", latex: "\\gg" },
                    { name: "Not Less", latex: "\\nless" },
                    { name: "Not Greater", latex: "\\ngtr" },
                    { name: "Parallel", latex: "\\parallel" },
                    { name: "Perpendicular", latex: "\\perp" }
                ]
            },
            {
                name: "Set Notation",
                formulas: [
                    { name: "Element Of", latex: "\\in" },
                    { name: "Not Element Of", latex: "\\notin" },
                    { name: "Contains", latex: "\\ni" },
                    { name: "Subset", latex: "\\subset" },
                    { name: "Superset", latex: "\\supset" },
                    { name: "Subset or Equal", latex: "\\subseteq" },
                    { name: "Superset or Equal", latex: "\\supseteq" },
                    { name: "Not Subset", latex: "\\not\\subset" },
                    { name: "Union", latex: "\\cup" },
                    { name: "Intersection", latex: "\\cap" },
                    { name: "Set Minus", latex: "\\setminus" },
                    { name: "Empty Set", latex: "\\emptyset" },
                    { name: "Natural Numbers", latex: "\\mathbb{N}" },
                    { name: "Integers", latex: "\\mathbb{Z}" },
                    { name: "Rationals", latex: "\\mathbb{Q}" },
                    { name: "Reals", latex: "\\mathbb{R}" },
                    { name: "Complex", latex: "\\mathbb{C}" },
                    { name: "For All", latex: "\\forall" },
                    { name: "Exists", latex: "\\exists" },
                    { name: "Not Exists", latex: "\\nexists" }
                ]
            },
            {
                name: "Logic Symbols",
                formulas: [
                    { name: "And (Conjunction)", latex: "\\land" },
                    { name: "Or (Disjunction)", latex: "\\lor" },
                    { name: "Not (Negation)", latex: "\\neg" },
                    { name: "Implies", latex: "\\Rightarrow" },
                    { name: "Implied By", latex: "\\Leftarrow" },
                    { name: "If and Only If", latex: "\\Leftrightarrow" },
                    { name: "Therefore", latex: "\\therefore" },
                    { name: "Because", latex: "\\because" },
                    { name: "True", latex: "\\top" },
                    { name: "False", latex: "\\bot" }
                ]
            },
            {
                name: "Arrows",
                formulas: [
                    { name: "Right Arrow", latex: "\\rightarrow" },
                    { name: "Left Arrow", latex: "\\leftarrow" },
                    { name: "Double Arrow", latex: "\\leftrightarrow" },
                    { name: "Long Right Arrow", latex: "\\longrightarrow" },
                    { name: "Long Left Arrow", latex: "\\longleftarrow" },
                    { name: "Maps To", latex: "\\mapsto" },
                    { name: "Implies", latex: "\\Rightarrow" },
                    { name: "Implied By", latex: "\\Leftarrow" },
                    { name: "If and Only If", latex: "\\Leftrightarrow" },
                    { name: "Up Arrow", latex: "\\uparrow" },
                    { name: "Down Arrow", latex: "\\downarrow" },
                    { name: "Up-Down Arrow", latex: "\\updownarrow" },
                    { name: "Northeast Arrow", latex: "\\nearrow" },
                    { name: "Southeast Arrow", latex: "\\searrow" },
                    { name: "Northwest Arrow", latex: "\\nwarrow" },
                    { name: "Southwest Arrow", latex: "\\swarrow" },
                    { name: "Hook Right", latex: "\\hookrightarrow" },
                    { name: "Hook Left", latex: "\\hookleftarrow" }
                ]
            },
            {
                name: "Miscellaneous",
                formulas: [
                    { name: "Infinity", latex: "\\infty" },
                    { name: "Partial", latex: "\\partial" },
                    { name: "Nabla", latex: "\\nabla" },
                    { name: "Aleph", latex: "\\aleph" },
                    { name: "Hbar", latex: "\\hbar" },
                    { name: "Ellipsis", latex: "\\ldots" },
                    { name: "Centered Dots", latex: "\\cdots" },
                    { name: "Vertical Dots", latex: "\\vdots" },
                    { name: "Diagonal Dots", latex: "\\ddots" },
                    { name: "Triangle", latex: "\\triangle" },
                    { name: "Square", latex: "\\square" },
                    { name: "Diamond", latex: "\\diamond" },
                    { name: "Check Mark", latex: "\\checkmark" },
                    { name: "Cross", latex: "\\times" },
                    { name: "Angle", latex: "\\angle" },
                    { name: "Measured Angle", latex: "\\measuredangle" }
                ]
            }
        ]
    },
    common: {
        title: "Common Formulas",
        sections: [
            {
                name: "Algebra",
                formulas: [
                    { name: "Quadratic Formula", latex: "x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}" },
                    { name: "Binomial Square", latex: "(a+b)^2 = a^2 + 2ab + b^2" },
                    { name: "Binomial Square Negative", latex: "(a-b)^2 = a^2 - 2ab + b^2" },
                    { name: "Difference of Squares", latex: "a^2 - b^2 = (a+b)(a-b)" },
                    { name: "Binomial Cube", latex: "(a+b)^3 = a^3 + 3a^2b + 3ab^2 + b^3" },
                    { name: "Binomial Cube Negative", latex: "(a-b)^3 = a^3 - 3a^2b + 3ab^2 - b^3" },
                    { name: "Sum of Cubes", latex: "a^3 + b^3 = (a+b)(a^2 - ab + b^2)" },
                    { name: "Difference of Cubes", latex: "a^3 - b^3 = (a-b)(a^2 + ab + b^2)" },
                    { name: "Binomial Theorem", latex: "(a+b)^n = \\sum_{k=0}^{n} \\binom{n}{k} a^{n-k}b^k" },
                    { name: "Arithmetic Sequence", latex: "a_n = a_1 + (n-1)d" },
                    { name: "Geometric Sequence", latex: "a_n = a_1 \\cdot r^{n-1}" },
                    { name: "Arithmetic Sum", latex: "S_n = \\frac{n(a_1 + a_n)}{2}" },
                    { name: "Geometric Sum", latex: "S_n = a_1 \\cdot \\frac{1-r^n}{1-r}" },
                    { name: "Infinite Geometric Sum", latex: "S = \\frac{a_1}{1-r}, |r| < 1" },
                    { name: "Logarithm Product", latex: "\\log(ab) = \\log a + \\log b" },
                    { name: "Logarithm Quotient", latex: "\\log\\frac{a}{b} = \\log a - \\log b" },
                    { name: "Logarithm Power", latex: "\\log a^n = n \\log a" },
                    { name: "Change of Base", latex: "\\log_b a = \\frac{\\ln a}{\\ln b}" },
                    { name: "Exponential", latex: "e^x" },
                    { name: "Natural Log", latex: "\\ln x" },
                    { name: "Logarithm Definition", latex: "\\log_b x = y \\Leftrightarrow b^y = x" },
                    { name: "Common Log", latex: "\\log_{10} x" },
                    { name: "Exponent Rules", latex: "a^m \\cdot a^n = a^{m+n}" },
                    { name: "Exponent Division", latex: "\\frac{a^m}{a^n} = a^{m-n}" },
                    { name: "Power of Power", latex: "(a^m)^n = a^{mn}" },
                    { name: "Complex Number", latex: "z = a + bi" },
                    { name: "Complex Modulus", latex: "|z| = \\sqrt{a^2 + b^2}" },
                    { name: "Euler's Formula", latex: "e^{i\\theta} = \\cos\\theta + i\\sin\\theta" }
                ]
            },
            {
                name: "Geometry",
                formulas: [
                    { name: "Pythagorean Theorem", latex: "a^2 + b^2 = c^2" },
                    { name: "Area of Circle", latex: "A = \\pi r^2" },
                    { name: "Circumference", latex: "C = 2\\pi r" },
                    { name: "Diameter", latex: "d = 2r" },
                    { name: "Arc Length", latex: "s = r\\theta" },
                    { name: "Sector Area", latex: "A = \\frac{1}{2}r^2\\theta" },
                    { name: "Area of Triangle", latex: "A = \\frac{1}{2}bh" },
                    { name: "Heron's Formula", latex: "A = \\sqrt{s(s-a)(s-b)(s-c)}" },
                    { name: "Area of Rectangle", latex: "A = lw" },
                    { name: "Area of Square", latex: "A = s^2" },
                    { name: "Area of Parallelogram", latex: "A = bh" },
                    { name: "Area of Trapezoid", latex: "A = \\frac{1}{2}(b_1 + b_2)h" },
                    { name: "Area of Rhombus", latex: "A = \\frac{1}{2}d_1 d_2" },
                    { name: "Area of Ellipse", latex: "A = \\pi ab" },
                    { name: "Perimeter of Rectangle", latex: "P = 2(l + w)" },
                    { name: "Volume of Sphere", latex: "V = \\frac{4}{3}\\pi r^3" },
                    { name: "Surface Area of Sphere", latex: "A = 4\\pi r^2" },
                    { name: "Volume of Cylinder", latex: "V = \\pi r^2 h" },
                    { name: "Surface Area of Cylinder", latex: "A = 2\\pi r(r + h)" },
                    { name: "Volume of Cone", latex: "V = \\frac{1}{3}\\pi r^2 h" },
                    { name: "Volume of Cube", latex: "V = s^3" },
                    { name: "Volume of Rectangular Prism", latex: "V = lwh" },
                    { name: "Volume of Pyramid", latex: "V = \\frac{1}{3}Bh" },
                    { name: "Distance Formula (2D)", latex: "d = \\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}" },
                    { name: "Distance Formula (3D)", latex: "d = \\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2 + (z_2-z_1)^2}" },
                    { name: "Midpoint Formula", latex: "M = \\left(\\frac{x_1+x_2}{2}, \\frac{y_1+y_2}{2}\\right)" },
                    { name: "Slope Formula", latex: "m = \\frac{y_2 - y_1}{x_2 - x_1}" },
                    { name: "Slope-Intercept Form", latex: "y = mx + b" },
                    { name: "Point-Slope Form", latex: "y - y_1 = m(x - x_1)" },
                    { name: "Standard Form", latex: "Ax + By = C" },
                    { name: "Circle Equation", latex: "(x-h)^2 + (y-k)^2 = r^2" },
                    { name: "Ellipse Equation", latex: "\\frac{(x-h)^2}{a^2} + \\frac{(y-k)^2}{b^2} = 1" },
                    { name: "Parabola Equation", latex: "y = a(x-h)^2 + k" },
                    { name: "Hyperbola Equation", latex: "\\frac{(x-h)^2}{a^2} - \\frac{(y-k)^2}{b^2} = 1" }
                ]
            },
            {
                name: "Trigonometry",
                formulas: [
                    { name: "Sine", latex: "\\sin\\theta = \\frac{\\text{opposite}}{\\text{hypotenuse}}" },
                    { name: "Cosine", latex: "\\cos\\theta = \\frac{\\text{adjacent}}{\\text{hypotenuse}}" },
                    { name: "Tangent", latex: "\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}" },
                    { name: "Cosecant", latex: "\\csc\\theta = \\frac{1}{\\sin\\theta}" },
                    { name: "Secant", latex: "\\sec\\theta = \\frac{1}{\\cos\\theta}" },
                    { name: "Cotangent", latex: "\\cot\\theta = \\frac{1}{\\tan\\theta}" },
                    { name: "Pythagorean Identity", latex: "\\sin^2\\theta + \\cos^2\\theta = 1" },
                    { name: "Pythagorean Identity 2", latex: "1 + \\tan^2\\theta = \\sec^2\\theta" },
                    { name: "Pythagorean Identity 3", latex: "1 + \\cot^2\\theta = \\csc^2\\theta" },
                    { name: "Sine Double Angle", latex: "\\sin 2\\theta = 2\\sin\\theta\\cos\\theta" },
                    { name: "Cosine Double Angle", latex: "\\cos 2\\theta = \\cos^2\\theta - \\sin^2\\theta" },
                    { name: "Cosine Double Angle 2", latex: "\\cos 2\\theta = 2\\cos^2\\theta - 1" },
                    { name: "Cosine Double Angle 3", latex: "\\cos 2\\theta = 1 - 2\\sin^2\\theta" },
                    { name: "Tan Double Angle", latex: "\\tan 2\\theta = \\frac{2\\tan\\theta}{1-\\tan^2\\theta}" },
                    { name: "Sine Half Angle", latex: "\\sin\\frac{\\theta}{2} = \\pm\\sqrt{\\frac{1-\\cos\\theta}{2}}" },
                    { name: "Cosine Half Angle", latex: "\\cos\\frac{\\theta}{2} = \\pm\\sqrt{\\frac{1+\\cos\\theta}{2}}" },
                    { name: "Sum of Angles Sin", latex: "\\sin(A+B) = \\sin A\\cos B + \\cos A\\sin B" },
                    { name: "Sum of Angles Cos", latex: "\\cos(A+B) = \\cos A\\cos B - \\sin A\\sin B" },
                    { name: "Law of Sines", latex: "\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C}" },
                    { name: "Law of Cosines", latex: "c^2 = a^2 + b^2 - 2ab\\cos C" },
                    { name: "Law of Tangents", latex: "\\frac{a-b}{a+b} = \\frac{\\tan\\frac{A-B}{2}}{\\tan\\frac{A+B}{2}}" },
                    { name: "Area with Sine", latex: "A = \\frac{1}{2}ab\\sin C" },
                    { name: "Inverse Sine", latex: "\\sin^{-1}x = \\arcsin x" },
                    { name: "Inverse Cosine", latex: "\\cos^{-1}x = \\arccos x" },
                    { name: "Inverse Tangent", latex: "\\tan^{-1}x = \\arctan x" },
                    { name: "Radians to Degrees", latex: "\\theta_{deg} = \\theta_{rad} \\cdot \\frac{180}{\\pi}" },
                    { name: "Degrees to Radians", latex: "\\theta_{rad} = \\theta_{deg} \\cdot \\frac{\\pi}{180}" }
                ]
            },
            {
                name: "Statistics & Probability",
                formulas: [
                    { name: "Mean", latex: "\\bar{x} = \\frac{\\sum x_i}{n}" },
                    { name: "Weighted Mean", latex: "\\bar{x} = \\frac{\\sum w_i x_i}{\\sum w_i}" },
                    { name: "Median", latex: "\\text{Med} = x_{(n+1)/2}" },
                    { name: "Mode", latex: "\\text{Mode} = \\text{most frequent value}" },
                    { name: "Range", latex: "R = x_{max} - x_{min}" },
                    { name: "Variance (Population)", latex: "\\sigma^2 = \\frac{\\sum(x_i - \\mu)^2}{N}" },
                    { name: "Variance (Sample)", latex: "s^2 = \\frac{\\sum(x_i - \\bar{x})^2}{n-1}" },
                    { name: "Standard Deviation", latex: "\\sigma = \\sqrt{\\frac{\\sum(x_i - \\mu)^2}{N}}" },
                    { name: "Z-Score", latex: "z = \\frac{x - \\mu}{\\sigma}" },
                    { name: "Covariance", latex: "\\text{Cov}(X,Y) = \\frac{\\sum(x_i-\\bar{x})(y_i-\\bar{y})}{n-1}" },
                    { name: "Correlation", latex: "r = \\frac{\\text{Cov}(X,Y)}{\\sigma_X \\sigma_Y}" },
                    { name: "Combination", latex: "\\binom{n}{r} = \\frac{n!}{r!(n-r)!}" },
                    { name: "Permutation", latex: "P(n,r) = \\frac{n!}{(n-r)!}" },
                    { name: "Factorial", latex: "n! = n \\cdot (n-1) \\cdot (n-2) \\cdots 2 \\cdot 1" },
                    { name: "Probability", latex: "P(A) = \\frac{n(A)}{n(S)}" },
                    { name: "Complement", latex: "P(A') = 1 - P(A)" },
                    { name: "Union", latex: "P(A \\cup B) = P(A) + P(B) - P(A \\cap B)" },
                    { name: "Conditional Probability", latex: "P(A|B) = \\frac{P(A \\cap B)}{P(B)}" },
                    { name: "Bayes' Theorem", latex: "P(A|B) = \\frac{P(B|A)P(A)}{P(B)}" },
                    { name: "Expected Value", latex: "E(X) = \\sum x_i P(x_i)" },
                    { name: "Binomial Distribution", latex: "P(X=k) = \\binom{n}{k}p^k(1-p)^{n-k}" },
                    { name: "Normal Distribution", latex: "f(x) = \\frac{1}{\\sigma\\sqrt{2\\pi}}e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}" },
                    { name: "Poisson Distribution", latex: "P(X=k) = \\frac{\\lambda^k e^{-\\lambda}}{k!}" }
                ]
            },
            {
                name: "Calculus Basics",
                formulas: [
                    { name: "Limit Definition", latex: "\\lim_{x \\to a} f(x) = L" },
                    { name: "Derivative Definition", latex: "f'(x) = \\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}" },
                    { name: "Power Rule", latex: "\\frac{d}{dx}x^n = nx^{n-1}" },
                    { name: "Constant Rule", latex: "\\frac{d}{dx}c = 0" },
                    { name: "Sum Rule", latex: "\\frac{d}{dx}[f+g] = f' + g'" },
                    { name: "Product Rule", latex: "\\frac{d}{dx}[fg] = f'g + fg'" },
                    { name: "Quotient Rule", latex: "\\frac{d}{dx}\\left[\\frac{f}{g}\\right] = \\frac{f'g - fg'}{g^2}" },
                    { name: "Chain Rule", latex: "\\frac{d}{dx}f(g(x)) = f'(g(x)) \\cdot g'(x)" },
                    { name: "Derivative of sin", latex: "\\frac{d}{dx}\\sin x = \\cos x" },
                    { name: "Derivative of cos", latex: "\\frac{d}{dx}\\cos x = -\\sin x" },
                    { name: "Derivative of tan", latex: "\\frac{d}{dx}\\tan x = \\sec^2 x" },
                    { name: "Derivative of e^x", latex: "\\frac{d}{dx}e^x = e^x" },
                    { name: "Derivative of ln", latex: "\\frac{d}{dx}\\ln x = \\frac{1}{x}" },
                    { name: "Integral Power Rule", latex: "\\int x^n dx = \\frac{x^{n+1}}{n+1} + C" },
                    { name: "Integral of sin", latex: "\\int \\sin x \\, dx = -\\cos x + C" },
                    { name: "Integral of cos", latex: "\\int \\cos x \\, dx = \\sin x + C" },
                    { name: "Integral of e^x", latex: "\\int e^x dx = e^x + C" },
                    { name: "Integral of 1/x", latex: "\\int \\frac{1}{x} dx = \\ln|x| + C" },
                    { name: "Definite Integral", latex: "\\int_a^b f(x) dx = F(b) - F(a)" },
                    { name: "Area Under Curve", latex: "A = \\int_a^b f(x) dx" }
                ]
            }
        ]
    },
    physics: {
        title: "Physics",
        sections: [
            {
                name: "Mechanics",
                formulas: [
                    { name: "Velocity", latex: "v = \\frac{\\Delta x}{\\Delta t}" },
                    { name: "Average Velocity", latex: "\\bar{v} = \\frac{x_f - x_i}{t_f - t_i}" },
                    { name: "Acceleration", latex: "a = \\frac{\\Delta v}{\\Delta t}" },
                    { name: "Kinematic Eq 1", latex: "v = u + at" },
                    { name: "Kinematic Eq 2", latex: "s = ut + \\frac{1}{2}at^2" },
                    { name: "Kinematic Eq 3", latex: "v^2 = u^2 + 2as" },
                    { name: "Kinematic Eq 4", latex: "s = \\frac{(u+v)}{2}t" },
                    { name: "Newton's 1st Law", latex: "\\sum \\vec{F} = 0 \\Rightarrow \\vec{v} = \\text{const}" },
                    { name: "Newton's 2nd Law", latex: "\\vec{F} = m\\vec{a}" },
                    { name: "Newton's 3rd Law", latex: "\\vec{F}_{12} = -\\vec{F}_{21}" },
                    { name: "Weight", latex: "W = mg" },
                    { name: "Momentum", latex: "\\vec{p} = m\\vec{v}" },
                    { name: "Impulse", latex: "\\vec{J} = \\vec{F}\\Delta t = \\Delta\\vec{p}" },
                    { name: "Conservation of Momentum", latex: "m_1v_1 + m_2v_2 = m_1v_1' + m_2v_2'" },
                    { name: "Kinetic Energy", latex: "KE = \\frac{1}{2}mv^2" },
                    { name: "Potential Energy (Gravity)", latex: "PE = mgh" },
                    { name: "Elastic PE", latex: "PE = \\frac{1}{2}kx^2" },
                    { name: "Work", latex: "W = \\vec{F} \\cdot \\vec{d} = Fd\\cos\\theta" },
                    { name: "Work-Energy Theorem", latex: "W_{net} = \\Delta KE" },
                    { name: "Power", latex: "P = \\frac{W}{t} = \\vec{F} \\cdot \\vec{v}" },
                    { name: "Static Friction", latex: "f_s \\leq \\mu_s N" },
                    { name: "Kinetic Friction", latex: "f_k = \\mu_k N" },
                    { name: "Centripetal Acceleration", latex: "a_c = \\frac{v^2}{r} = \\omega^2 r" },
                    { name: "Centripetal Force", latex: "F_c = \\frac{mv^2}{r}" },
                    { name: "Universal Gravitation", latex: "F = G\\frac{m_1 m_2}{r^2}" },
                    { name: "Gravitational Field", latex: "g = \\frac{GM}{r^2}" },
                    { name: "Orbital Velocity", latex: "v = \\sqrt{\\frac{GM}{r}}" },
                    { name: "Escape Velocity", latex: "v_e = \\sqrt{\\frac{2GM}{r}}" },
                    { name: "Kepler's 3rd Law", latex: "T^2 = \\frac{4\\pi^2}{GM}r^3" }
                ]
            },
            {
                name: "Rotational Mechanics",
                formulas: [
                    { name: "Angular Velocity", latex: "\\omega = \\frac{\\Delta\\theta}{\\Delta t}" },
                    { name: "Angular Acceleration", latex: "\\alpha = \\frac{\\Delta\\omega}{\\Delta t}" },
                    { name: "Linear-Angular Relation", latex: "v = r\\omega" },
                    { name: "Tangential Acceleration", latex: "a_t = r\\alpha" },
                    { name: "Rotational Kinematic 1", latex: "\\omega = \\omega_0 + \\alpha t" },
                    { name: "Rotational Kinematic 2", latex: "\\theta = \\omega_0 t + \\frac{1}{2}\\alpha t^2" },
                    { name: "Rotational Kinematic 3", latex: "\\omega^2 = \\omega_0^2 + 2\\alpha\\theta" },
                    { name: "Torque", latex: "\\tau = r F \\sin\\theta = r \\times F" },
                    { name: "Newton's 2nd for Rotation", latex: "\\tau = I\\alpha" },
                    { name: "Moment of Inertia", latex: "I = \\sum m_i r_i^2" },
                    { name: "I (Solid Cylinder)", latex: "I = \\frac{1}{2}MR^2" },
                    { name: "I (Solid Sphere)", latex: "I = \\frac{2}{5}MR^2" },
                    { name: "I (Hollow Sphere)", latex: "I = \\frac{2}{3}MR^2" },
                    { name: "I (Rod, Center)", latex: "I = \\frac{1}{12}ML^2" },
                    { name: "I (Rod, End)", latex: "I = \\frac{1}{3}ML^2" },
                    { name: "Parallel Axis Theorem", latex: "I = I_{cm} + Md^2" },
                    { name: "Rotational KE", latex: "KE_{rot} = \\frac{1}{2}I\\omega^2" },
                    { name: "Angular Momentum", latex: "L = I\\omega" },
                    { name: "Conservation of L", latex: "I_1\\omega_1 = I_2\\omega_2" },
                    { name: "Rolling without Slipping", latex: "v_{cm} = R\\omega" }
                ]
            },
            {
                name: "Oscillations & Waves",
                formulas: [
                    { name: "SHM Displacement", latex: "x = A\\cos(\\omega t + \\phi)" },
                    { name: "SHM Velocity", latex: "v = -A\\omega\\sin(\\omega t + \\phi)" },
                    { name: "SHM Acceleration", latex: "a = -\\omega^2 x" },
                    { name: "Angular Frequency", latex: "\\omega = 2\\pi f = \\frac{2\\pi}{T}" },
                    { name: "Period (Spring)", latex: "T = 2\\pi\\sqrt{\\frac{m}{k}}" },
                    { name: "Period (Pendulum)", latex: "T = 2\\pi\\sqrt{\\frac{L}{g}}" },
                    { name: "Wave Speed", latex: "v = f\\lambda" },
                    { name: "Period", latex: "T = \\frac{1}{f}" },
                    { name: "Wave Equation", latex: "y = A\\sin(kx - \\omega t)" },
                    { name: "Wave Number", latex: "k = \\frac{2\\pi}{\\lambda}" },
                    { name: "Speed on String", latex: "v = \\sqrt{\\frac{T}{\\mu}}" },
                    { name: "Doppler Effect", latex: "f' = f\\frac{v \\pm v_o}{v \\mp v_s}" },
                    { name: "Beat Frequency", latex: "f_{beat} = |f_1 - f_2|" },
                    { name: "Standing Wave (Fixed)", latex: "\\lambda_n = \\frac{2L}{n}" },
                    { name: "Sound Intensity", latex: "I = \\frac{P}{4\\pi r^2}" },
                    { name: "Decibel Level", latex: "\\beta = 10\\log\\frac{I}{I_0}" }
                ]
            },
            {
                name: "Optics",
                formulas: [
                    { name: "Speed of Light", latex: "c = 3 \\times 10^8 \\text{ m/s}" },
                    { name: "Snell's Law", latex: "n_1\\sin\\theta_1 = n_2\\sin\\theta_2" },
                    { name: "Refractive Index", latex: "n = \\frac{c}{v}" },
                    { name: "Critical Angle", latex: "\\sin\\theta_c = \\frac{n_2}{n_1}" },
                    { name: "Mirror Equation", latex: "\\frac{1}{f} = \\frac{1}{d_o} + \\frac{1}{d_i}" },
                    { name: "Lens Equation", latex: "\\frac{1}{f} = \\frac{1}{d_o} + \\frac{1}{d_i}" },
                    { name: "Magnification", latex: "M = -\\frac{d_i}{d_o} = \\frac{h_i}{h_o}" },
                    { name: "Lens Power", latex: "P = \\frac{1}{f}" },
                    { name: "Lensmaker's Equation", latex: "\\frac{1}{f} = (n-1)\\left(\\frac{1}{R_1} - \\frac{1}{R_2}\\right)" },
                    { name: "Two Lens System", latex: "\\frac{1}{f} = \\frac{1}{f_1} + \\frac{1}{f_2}" },
                    { name: "Young's Double Slit", latex: "d\\sin\\theta = m\\lambda" },
                    { name: "Diffraction Grating", latex: "d\\sin\\theta = n\\lambda" },
                    { name: "Single Slit Minimum", latex: "a\\sin\\theta = m\\lambda" },
                    { name: "Thin Film Interference", latex: "2nt = (m + \\frac{1}{2})\\lambda" },
                    { name: "Brewster's Angle", latex: "\\tan\\theta_B = \\frac{n_2}{n_1}" }
                ]
            },
            {
                name: "Electricity",
                formulas: [
                    { name: "Coulomb's Law", latex: "F = k\\frac{q_1 q_2}{r^2}" },
                    { name: "Electric Field (Point)", latex: "E = k\\frac{Q}{r^2}" },
                    { name: "Electric Field (Definition)", latex: "\\vec{E} = \\frac{\\vec{F}}{q}" },
                    { name: "Electric Potential", latex: "V = k\\frac{Q}{r}" },
                    { name: "Potential Energy", latex: "U = k\\frac{q_1 q_2}{r}" },
                    { name: "Work by E-field", latex: "W = q\\Delta V" },
                    { name: "E from V", latex: "E = -\\frac{dV}{dx}" },
                    { name: "Parallel Plate E", latex: "E = \\frac{\\sigma}{\\epsilon_0} = \\frac{V}{d}" },
                    { name: "Capacitance", latex: "C = \\frac{Q}{V}" },
                    { name: "Parallel Plate C", latex: "C = \\epsilon_0 \\frac{A}{d}" },
                    { name: "Capacitor with Dielectric", latex: "C = \\kappa\\epsilon_0\\frac{A}{d}" },
                    { name: "Energy in Capacitor", latex: "U = \\frac{1}{2}CV^2 = \\frac{Q^2}{2C}" },
                    { name: "Capacitors in Series", latex: "\\frac{1}{C_{eq}} = \\frac{1}{C_1} + \\frac{1}{C_2}" },
                    { name: "Capacitors in Parallel", latex: "C_{eq} = C_1 + C_2" },
                    { name: "Ohm's Law", latex: "V = IR" },
                    { name: "Resistance", latex: "R = \\rho\\frac{L}{A}" },
                    { name: "Power (Electrical)", latex: "P = IV = I^2R = \\frac{V^2}{R}" },
                    { name: "Resistors in Series", latex: "R_{eq} = R_1 + R_2 + R_3" },
                    { name: "Resistors in Parallel", latex: "\\frac{1}{R_{eq}} = \\frac{1}{R_1} + \\frac{1}{R_2}" },
                    { name: "Kirchhoff's Current", latex: "\\sum I_{in} = \\sum I_{out}" },
                    { name: "Kirchhoff's Voltage", latex: "\\sum V = 0" },
                    { name: "RC Time Constant", latex: "\\tau = RC" },
                    { name: "RC Charging", latex: "Q = Q_0(1 - e^{-t/RC})" },
                    { name: "RC Discharging", latex: "Q = Q_0 e^{-t/RC}" }
                ]
            },
            {
                name: "Magnetism",
                formulas: [
                    { name: "Magnetic Force on Charge", latex: "\\vec{F} = q\\vec{v} \\times \\vec{B}" },
                    { name: "Magnetic Force on Wire", latex: "F = BIL\\sin\\theta" },
                    { name: "Lorentz Force", latex: "\\vec{F} = q(\\vec{E} + \\vec{v} \\times \\vec{B})" },
                    { name: "Circular Motion in B", latex: "r = \\frac{mv}{qB}" },
                    { name: "Magnetic Field (Wire)", latex: "B = \\frac{\\mu_0 I}{2\\pi r}" },
                    { name: "B (Center of Loop)", latex: "B = \\frac{\\mu_0 I}{2R}" },
                    { name: "B (Solenoid)", latex: "B = \\mu_0 n I" },
                    { name: "Magnetic Flux", latex: "\\Phi_B = BA\\cos\\theta" },
                    { name: "Faraday's Law", latex: "\\varepsilon = -N\\frac{d\\Phi_B}{dt}" },
                    { name: "Motional EMF", latex: "\\varepsilon = BLv" },
                    { name: "Lenz's Law", latex: "\\varepsilon = -\\frac{d\\Phi}{dt}" },
                    { name: "Inductance", latex: "L = \\frac{N\\Phi_B}{I}" },
                    { name: "Self-Induced EMF", latex: "\\varepsilon = -L\\frac{dI}{dt}" },
                    { name: "Energy in Inductor", latex: "U = \\frac{1}{2}LI^2" },
                    { name: "RL Time Constant", latex: "\\tau = \\frac{L}{R}" },
                    { name: "Transformer", latex: "\\frac{V_s}{V_p} = \\frac{N_s}{N_p}" }
                ]
            },
            {
                name: "Thermodynamics",
                formulas: [
                    { name: "Heat Transfer", latex: "Q = mc\\Delta T" },
                    { name: "Latent Heat", latex: "Q = mL" },
                    { name: "Heat Conduction", latex: "P = \\frac{kA\\Delta T}{L}" },
                    { name: "Ideal Gas Law", latex: "PV = nRT" },
                    { name: "Ideal Gas (Particles)", latex: "PV = Nk_BT" },
                    { name: "Kinetic Theory", latex: "KE_{avg} = \\frac{3}{2}k_BT" },
                    { name: "rms Speed", latex: "v_{rms} = \\sqrt{\\frac{3k_BT}{m}}" },
                    { name: "Internal Energy", latex: "U = \\frac{3}{2}nRT" },
                    { name: "First Law", latex: "\\Delta U = Q - W" },
                    { name: "Work (Isobaric)", latex: "W = P\\Delta V" },
                    { name: "Work (Isothermal)", latex: "W = nRT\\ln\\frac{V_f}{V_i}" },
                    { name: "Adiabatic Process", latex: "PV^\\gamma = \\text{const}" },
                    { name: "Efficiency (Heat Engine)", latex: "\\eta = 1 - \\frac{Q_C}{Q_H}" },
                    { name: "Carnot Efficiency", latex: "\\eta_C = 1 - \\frac{T_C}{T_H}" },
                    { name: "Entropy Change", latex: "\\Delta S = \\frac{Q_{rev}}{T}" },
                    { name: "Stefan-Boltzmann", latex: "P = \\sigma A T^4" },
                    { name: "Wien's Law", latex: "\\lambda_{max} T = 2.898 \\times 10^{-3}" },
                    { name: "Thermal Expansion (Linear)", latex: "\\Delta L = \\alpha L_0 \\Delta T" },
                    { name: "Thermal Expansion (Volume)", latex: "\\Delta V = \\beta V_0 \\Delta T" }
                ]
            },
            {
                name: "Fluid Mechanics",
                formulas: [
                    { name: "Density", latex: "\\rho = \\frac{m}{V}" },
                    { name: "Pressure", latex: "P = \\frac{F}{A}" },
                    { name: "Hydrostatic Pressure", latex: "P = P_0 + \\rho gh" },
                    { name: "Pascal's Principle", latex: "\\frac{F_1}{A_1} = \\frac{F_2}{A_2}" },
                    { name: "Buoyant Force", latex: "F_B = \\rho_f V_d g" },
                    { name: "Continuity Equation", latex: "A_1 v_1 = A_2 v_2" },
                    { name: "Bernoulli's Equation", latex: "P + \\frac{1}{2}\\rho v^2 + \\rho gh = \\text{const}" },
                    { name: "Torricelli's Theorem", latex: "v = \\sqrt{2gh}" },
                    { name: "Viscous Force", latex: "F = \\eta A \\frac{dv}{dy}" },
                    { name: "Stokes' Law", latex: "F = 6\\pi\\eta rv" },
                    { name: "Reynolds Number", latex: "Re = \\frac{\\rho vD}{\\eta}" }
                ]
            },
            {
                name: "Modern Physics",
                formulas: [
                    { name: "Mass-Energy", latex: "E = mc^2" },
                    { name: "Relativistic Energy", latex: "E = \\gamma mc^2" },
                    { name: "Lorentz Factor", latex: "\\gamma = \\frac{1}{\\sqrt{1-v^2/c^2}}" },
                    { name: "Relativistic Momentum", latex: "p = \\gamma mv" },
                    { name: "Time Dilation", latex: "\\Delta t = \\gamma \\Delta t_0" },
                    { name: "Length Contraction", latex: "L = \\frac{L_0}{\\gamma}" },
                    { name: "Photon Energy", latex: "E = hf = \\frac{hc}{\\lambda}" },
                    { name: "Photon Momentum", latex: "p = \\frac{h}{\\lambda} = \\frac{E}{c}" },
                    { name: "de Broglie Wavelength", latex: "\\lambda = \\frac{h}{p} = \\frac{h}{mv}" },
                    { name: "Photoelectric Effect", latex: "KE_{max} = hf - \\phi" },
                    { name: "Work Function", latex: "\\phi = hf_0" },
                    { name: "Heisenberg Uncertainty", latex: "\\Delta x \\cdot \\Delta p \\geq \\frac{\\hbar}{2}" },
                    { name: "Energy-Time Uncertainty", latex: "\\Delta E \\cdot \\Delta t \\geq \\frac{\\hbar}{2}" },
                    { name: "Bohr Radius", latex: "r_n = n^2 a_0" },
                    { name: "Bohr Energy Levels", latex: "E_n = -\\frac{13.6}{n^2} \\text{ eV}" },
                    { name: "Rydberg Formula", latex: "\\frac{1}{\\lambda} = R\\left(\\frac{1}{n_1^2} - \\frac{1}{n_2^2}\\right)" },
                    { name: "Radioactive Decay", latex: "N = N_0 e^{-\\lambda t}" },
                    { name: "Half-Life", latex: "t_{1/2} = \\frac{\\ln 2}{\\lambda}" },
                    { name: "Activity", latex: "A = \\lambda N = A_0 e^{-\\lambda t}" },
                    { name: "Binding Energy", latex: "E_b = (Zm_p + Nm_n - M)c^2" },
                    { name: "Mass Defect", latex: "\\Delta m = Zm_p + Nm_n - M" }
                ]
            }
        ]
    },
    chemistry: {
        title: "Chemistry",
        sections: [
            {
                name: "Stoichiometry",
                formulas: [
                    { name: "Molar Mass", latex: "M = \\frac{m}{n}" },
                    { name: "Number of Moles", latex: "n = \\frac{m}{M}" },
                    { name: "Avogadro's Number", latex: "N_A = 6.022 \\times 10^{23}" },
                    { name: "Number of Particles", latex: "N = n \\times N_A" },
                    { name: "Molar Volume (STP)", latex: "V_m = 22.4 \\text{ L/mol}" },
                    { name: "Molarity", latex: "M = \\frac{n}{V}" },
                    { name: "Molality", latex: "m = \\frac{n}{m_{solvent}}" },
                    { name: "Dilution", latex: "M_1V_1 = M_2V_2" },
                    { name: "Percent Composition", latex: "\\% = \\frac{m_{element}}{m_{compound}} \\times 100" },
                    { name: "Percent Yield", latex: "\\% = \\frac{\\text{actual}}{\\text{theoretical}} \\times 100" },
                    { name: "Empirical Formula", latex: "\\text{Divide by smallest ratio}" },
                    { name: "Molecular Formula", latex: "\\text{Molecular} = n \\times \\text{Empirical}" }
                ]
            },
            {
                name: "Gas Laws",
                formulas: [
                    { name: "Ideal Gas Law", latex: "PV = nRT" },
                    { name: "Boyle's Law", latex: "P_1V_1 = P_2V_2" },
                    { name: "Charles's Law", latex: "\\frac{V_1}{T_1} = \\frac{V_2}{T_2}" },
                    { name: "Gay-Lussac's Law", latex: "\\frac{P_1}{T_1} = \\frac{P_2}{T_2}" },
                    { name: "Combined Gas Law", latex: "\\frac{P_1V_1}{T_1} = \\frac{P_2V_2}{T_2}" },
                    { name: "Dalton's Law", latex: "P_{total} = P_1 + P_2 + P_3" },
                    { name: "Mole Fraction", latex: "X_A = \\frac{n_A}{n_{total}}" },
                    { name: "Partial Pressure", latex: "P_A = X_A \\cdot P_{total}" },
                    { name: "Graham's Law", latex: "\\frac{r_1}{r_2} = \\sqrt{\\frac{M_2}{M_1}}" },
                    { name: "Density of Gas", latex: "\\rho = \\frac{PM}{RT}" },
                    { name: "Van der Waals", latex: "\\left(P + \\frac{an^2}{V^2}\\right)(V-nb) = nRT" }
                ]
            },
            {
                name: "Chemical Reactions",
                formulas: [
                    { name: "Reaction Arrow", latex: "\\rightarrow" },
                    { name: "Reversible Reaction", latex: "\\rightleftharpoons" },
                    { name: "Precipitate", latex: "\\downarrow" },
                    { name: "Gas Evolved", latex: "\\uparrow" },
                    { name: "Heat Added", latex: "+\\Delta" },
                    { name: "Catalyst", latex: "\\xrightarrow{\\text{cat}}" },
                    { name: "Water", latex: "H_2O" },
                    { name: "Hydronium", latex: "H_3O^+" },
                    { name: "Hydroxide", latex: "OH^-" },
                    { name: "Carbon Dioxide", latex: "CO_2" },
                    { name: "Glucose", latex: "C_6H_{12}O_6" },
                    { name: "Ethanol", latex: "C_2H_5OH" },
                    { name: "Sulfuric Acid", latex: "H_2SO_4" },
                    { name: "Nitric Acid", latex: "HNO_3" },
                    { name: "Hydrochloric Acid", latex: "HCl" },
                    { name: "Sodium Hydroxide", latex: "NaOH" },
                    { name: "Ammonia", latex: "NH_3" },
                    { name: "Methane Combustion", latex: "CH_4 + 2O_2 \\rightarrow CO_2 + 2H_2O" },
                    { name: "Photosynthesis", latex: "6CO_2 + 6H_2O \\rightarrow C_6H_{12}O_6 + 6O_2" },
                    { name: "Cellular Respiration", latex: "C_6H_{12}O_6 + 6O_2 \\rightarrow 6CO_2 + 6H_2O" }
                ]
            },
            {
                name: "Thermochemistry",
                formulas: [
                    { name: "Enthalpy Change", latex: "\\Delta H = H_{products} - H_{reactants}" },
                    { name: "Exothermic Reaction", latex: "\\Delta H < 0" },
                    { name: "Endothermic Reaction", latex: "\\Delta H > 0" },
                    { name: "Gibbs Free Energy", latex: "\\Delta G = \\Delta H - T\\Delta S" },
                    { name: "Spontaneous Reaction", latex: "\\Delta G < 0" },
                    { name: "Hess's Law", latex: "\\Delta H_{rxn} = \\sum \\Delta H_f(products) - \\sum \\Delta H_f(reactants)" },
                    { name: "Heat Capacity (molar)", latex: "q = nC_p\\Delta T" },
                    { name: "Heat Capacity (mass)", latex: "q = mc\\Delta T" },
                    { name: "Bond Energy", latex: "\\Delta H = \\sum E_{broken} - \\sum E_{formed}" },
                    { name: "Entropy Change", latex: "\\Delta S = \\sum S_{products} - \\sum S_{reactants}" }
                ]
            },
            {
                name: "Kinetics",
                formulas: [
                    { name: "Reaction Rate", latex: "\\text{Rate} = -\\frac{\\Delta[A]}{\\Delta t}" },
                    { name: "Rate Law", latex: "\\text{Rate} = k[A]^m[B]^n" },
                    { name: "Zero Order Integrated", latex: "[A] = [A]_0 - kt" },
                    { name: "First Order Integrated", latex: "\\ln[A] = \\ln[A]_0 - kt" },
                    { name: "Second Order Integrated", latex: "\\frac{1}{[A]} = \\frac{1}{[A]_0} + kt" },
                    { name: "Half-Life (1st Order)", latex: "t_{1/2} = \\frac{\\ln 2}{k}" },
                    { name: "Half-Life (2nd Order)", latex: "t_{1/2} = \\frac{1}{k[A]_0}" },
                    { name: "Arrhenius Equation", latex: "k = Ae^{-E_a/RT}" },
                    { name: "Two-Point Arrhenius", latex: "\\ln\\frac{k_2}{k_1} = \\frac{E_a}{R}\\left(\\frac{1}{T_1} - \\frac{1}{T_2}\\right)" },
                    { name: "Activation Energy", latex: "\\ln k = \\ln A - \\frac{E_a}{RT}" }
                ]
            },
            {
                name: "Equilibrium",
                formulas: [
                    { name: "Equilibrium Constant", latex: "K_{eq} = \\frac{[C]^c[D]^d}{[A]^a[B]^b}" },
                    { name: "Kp and Kc Relation", latex: "K_p = K_c(RT)^{\\Delta n}" },
                    { name: "Reaction Quotient", latex: "Q = \\frac{[C]^c[D]^d}{[A]^a[B]^b}" },
                    { name: "Le Chatelier's Principle", latex: "Q < K \\Rightarrow \\text{forward}" },
                    { name: "ICE Table Method", latex: "K = \\frac{(x)(x)}{([A]_0-x)([B]_0-x)}" },
                    { name: "Solubility Product", latex: "K_{sp} = [A^+]^a[B^-]^b" },
                    { name: "Common Ion Effect", latex: "\\text{Decreases solubility}" }
                ]
            },
            {
                name: "Acids & Bases",
                formulas: [
                    { name: "pH Definition", latex: "pH = -\\log[H^+]" },
                    { name: "pOH Definition", latex: "pOH = -\\log[OH^-]" },
                    { name: "pH + pOH", latex: "pH + pOH = 14" },
                    { name: "pKa Definition", latex: "pK_a = -\\log K_a" },
                    { name: "Ka Expression", latex: "K_a = \\frac{[H^+][A^-]}{[HA]}" },
                    { name: "Kb Expression", latex: "K_b = \\frac{[BH^+][OH^-]}{[B]}" },
                    { name: "Ka × Kb", latex: "K_a \\times K_b = K_w = 10^{-14}" },
                    { name: "Henderson-Hasselbalch", latex: "pH = pK_a + \\log\\frac{[A^-]}{[HA]}" },
                    { name: "Buffer Capacity", latex: "\\beta = \\frac{\\Delta n}{\\Delta pH}" },
                    { name: "Weak Acid pH", latex: "[H^+] = \\sqrt{K_a \\cdot C_a}" },
                    { name: "Strong Acid pH", latex: "pH = -\\log[H^+]" },
                    { name: "Neutralization", latex: "HA + BOH \\rightarrow BA + H_2O" },
                    { name: "Titration Endpoint", latex: "n_{acid} = n_{base}" }
                ]
            },
            {
                name: "Electrochemistry",
                formulas: [
                    { name: "Cell Notation", latex: "\\text{Anode} | \\text{solution} || \\text{solution} | \\text{Cathode}" },
                    { name: "Cell Potential", latex: "E^\\circ_{cell} = E^\\circ_{cathode} - E^\\circ_{anode}" },
                    { name: "Nernst Equation", latex: "E = E^\\circ - \\frac{0.0592}{n}\\log Q" },
                    { name: "Gibbs and E", latex: "\\Delta G^\\circ = -nFE^\\circ" },
                    { name: "Equilibrium and E", latex: "E^\\circ = \\frac{0.0592}{n}\\log K" },
                    { name: "Faraday's Law", latex: "m = \\frac{MIt}{nF}" },
                    { name: "Charge", latex: "Q = It" },
                    { name: "Current Efficiency", latex: "\\% = \\frac{m_{actual}}{m_{theoretical}} \\times 100" }
                ]
            },
            {
                name: "Atomic Structure",
                formulas: [
                    { name: "Atomic Number", latex: "Z = \\text{number of protons}" },
                    { name: "Mass Number", latex: "A = Z + N" },
                    { name: "Isotope Notation", latex: "^A_Z X" },
                    { name: "Planck's Equation", latex: "E = hf = \\frac{hc}{\\lambda}" },
                    { name: "de Broglie", latex: "\\lambda = \\frac{h}{mv}" },
                    { name: "Bohr Energy Levels", latex: "E_n = -\\frac{13.6}{n^2} \\text{ eV}" },
                    { name: "Electron Configuration", latex: "1s^2 2s^2 2p^6 \\ldots" },
                    { name: "Orbital Shapes", latex: "s, p, d, f" },
                    { name: "Pauli Exclusion", latex: "\\text{Max 2 electrons per orbital}" },
                    { name: "Hund's Rule", latex: "\\text{Fill orbitals singly first}" }
                ]
            }
        ]
    },
    advanced: {
        title: "Advanced",
        formulas: [
            { name: "Integral", latex: "\\int_{a}^{b} f(x) dx" },
            { name: "Double Integral", latex: "\\iint_R f(x,y) \\, dA" },
            { name: "Triple Integral", latex: "\\iiint_V f(x,y,z) \\, dV" },
            { name: "Line Integral", latex: "\\oint_C \\vec{F} \\cdot d\\vec{r}" },
            { name: "Surface Integral", latex: "\\iint_S \\vec{F} \\cdot d\\vec{S}" },
            { name: "Derivative", latex: "\\frac{d}{dx}f(x)" },
            { name: "Partial Derivative", latex: "\\frac{\\partial f}{\\partial x}" },
            { name: "Second Derivative", latex: "\\frac{d^2 y}{dx^2}" },
            { name: "Mixed Partial", latex: "\\frac{\\partial^2 f}{\\partial x \\partial y}" },
            { name: "Gradient", latex: "\\nabla f = \\frac{\\partial f}{\\partial x}\\hat{i} + \\frac{\\partial f}{\\partial y}\\hat{j}" },
            { name: "Divergence", latex: "\\nabla \\cdot \\vec{F} = \\frac{\\partial P}{\\partial x} + \\frac{\\partial Q}{\\partial y}" },
            { name: "Curl", latex: "\\nabla \\times \\vec{F}" },
            { name: "Laplacian", latex: "\\nabla^2 f = \\frac{\\partial^2 f}{\\partial x^2} + \\frac{\\partial^2 f}{\\partial y^2}" },
            { name: "Directional Derivative", latex: "D_u f = \\nabla f \\cdot \\hat{u}" },
            { name: "Limit", latex: "\\lim_{x \\to a} f(x) = L" },
            { name: "Limit at Infinity", latex: "\\lim_{x \\to \\infty} f(x)" },
            { name: "L'Hôpital's Rule", latex: "\\lim_{x \\to a} \\frac{f(x)}{g(x)} = \\lim_{x \\to a} \\frac{f'(x)}{g'(x)}" },
            { name: "Taylor Series", latex: "f(x) = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(a)}{n!}(x-a)^n" },
            { name: "Maclaurin Series", latex: "f(x) = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(0)}{n!}x^n" },
            { name: "e^x Series", latex: "e^x = \\sum_{n=0}^{\\infty} \\frac{x^n}{n!}" },
            { name: "sin x Series", latex: "\\sin x = \\sum_{n=0}^{\\infty} \\frac{(-1)^n x^{2n+1}}{(2n+1)!}" },
            { name: "cos x Series", latex: "\\cos x = \\sum_{n=0}^{\\infty} \\frac{(-1)^n x^{2n}}{(2n)!}" },
            { name: "Fourier Series", latex: "f(x) = \\frac{a_0}{2} + \\sum_{n=1}^{\\infty}(a_n\\cos nx + b_n\\sin nx)" },
            { name: "Fourier Coefficient a_n", latex: "a_n = \\frac{1}{\\pi}\\int_{-\\pi}^{\\pi} f(x)\\cos(nx)dx" },
            { name: "Fourier Coefficient b_n", latex: "b_n = \\frac{1}{\\pi}\\int_{-\\pi}^{\\pi} f(x)\\sin(nx)dx" },
            { name: "Integration by Parts", latex: "\\int u \\, dv = uv - \\int v \\, du" },
            { name: "U-Substitution", latex: "\\int f(g(x))g'(x)dx = \\int f(u)du" },
            { name: "Partial Fractions", latex: "\\frac{P(x)}{Q(x)} = \\frac{A}{x-a} + \\frac{B}{x-b}" },
            { name: "Arc Length", latex: "s = \\int_a^b \\sqrt{1 + (f'(x))^2} dx" },
            { name: "Surface Area (Revolution)", latex: "A = 2\\pi \\int_a^b f(x)\\sqrt{1+(f'(x))^2}dx" },
            { name: "Volume (Disk Method)", latex: "V = \\pi \\int_a^b [f(x)]^2 dx" },
            { name: "Volume (Shell Method)", latex: "V = 2\\pi \\int_a^b x f(x) dx" },
            { name: "Sum", latex: "\\sum_{n=1}^{\\infty} a_n" },
            { name: "Product", latex: "\\prod_{i=1}^{n} x_i" },
            { name: "Geometric Series", latex: "\\sum_{n=0}^{\\infty} ar^n = \\frac{a}{1-r}" },
            { name: "P-Series", latex: "\\sum_{n=1}^{\\infty} \\frac{1}{n^p}" },
            { name: "Ratio Test", latex: "\\lim_{n \\to \\infty} \\left|\\frac{a_{n+1}}{a_n}\\right| < 1" },
            { name: "Root Test", latex: "\\lim_{n \\to \\infty} \\sqrt[n]{|a_n|} < 1" },
            { name: "2x2 Matrix", latex: "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}" },
            { name: "3x3 Matrix", latex: "\\begin{pmatrix} a & b & c \\\\ d & e & f \\\\ g & h & i \\end{pmatrix}" },
            { name: "2x2 Determinant", latex: "\\det(A) = ad - bc" },
            { name: "3x3 Determinant", latex: "\\det(A) = a(ei-fh) - b(di-fg) + c(dh-eg)" },
            { name: "Matrix Multiplication", latex: "C_{ij} = \\sum_k A_{ik}B_{kj}" },
            { name: "Matrix Transpose", latex: "(A^T)_{ij} = A_{ji}" },
            { name: "Matrix Inverse", latex: "AA^{-1} = I" },
            { name: "Eigenvalues", latex: "\\det(A - \\lambda I) = 0" },
            { name: "Eigenvector", latex: "(A - \\lambda I)\\vec{v} = 0" },
            { name: "Dot Product", latex: "\\vec{a} \\cdot \\vec{b} = |a||b|\\cos\\theta" },
            { name: "Cross Product", latex: "\\vec{a} \\times \\vec{b} = |a||b|\\sin\\theta \\, \\hat{n}" },
            { name: "1st Order ODE", latex: "\\frac{dy}{dx} + P(x)y = Q(x)" },
            { name: "Separable ODE", latex: "\\frac{dy}{dx} = f(x)g(y)" },
            { name: "2nd Order ODE", latex: "ay'' + by' + cy = 0" },
            { name: "Characteristic Equation", latex: "ar^2 + br + c = 0" },
            { name: "Laplace Transform", latex: "\\mathcal{L}\\{f(t)\\} = \\int_0^\\infty e^{-st}f(t)dt" },
            { name: "Inverse Laplace", latex: "\\mathcal{L}^{-1}\\{F(s)\\}" },
            { name: "Green's Theorem", latex: "\\oint_C (Pdx + Qdy) = \\iint_R \\left(\\frac{\\partial Q}{\\partial x} - \\frac{\\partial P}{\\partial y}\\right)dA" },
            { name: "Stokes' Theorem", latex: "\\oint_C \\vec{F} \\cdot d\\vec{r} = \\iint_S (\\nabla \\times \\vec{F}) \\cdot d\\vec{S}" },
            { name: "Divergence Theorem", latex: "\\iiint_V (\\nabla \\cdot \\vec{F})dV = \\iint_S \\vec{F} \\cdot d\\vec{S}" },
            { name: "System of Equations", latex: "\\begin{cases} ax + by = c \\\\ dx + ey = f \\end{cases}" },
            { name: "Piecewise Function", latex: "f(x) = \\begin{cases} x & x \\geq 0 \\\\ -x & x < 0 \\end{cases}" },
            { name: "Gamma Function", latex: "\\Gamma(n) = \\int_0^\\infty x^{n-1}e^{-x}dx" },
            { name: "Beta Function", latex: "B(x,y) = \\int_0^1 t^{x-1}(1-t)^{y-1}dt" },
            { name: "Complex Exponential", latex: "e^{i\\theta} = \\cos\\theta + i\\sin\\theta" },
            { name: "De Moivre's Theorem", latex: "(\\cos\\theta + i\\sin\\theta)^n = \\cos n\\theta + i\\sin n\\theta" }
        ]
    }
};
