-- ============================================================================
-- RETIRED — DO NOT PASTE THIS FILE. It no longer contains any SQL.
--
-- This was a consolidated catch-up script: ~3,650 lines of function bodies
-- copied out of supabase/migrations/, meant to be pasted once to bring a
-- database up to date. It worked, right up until it silently stopped being
-- true.
--
-- WHY IT WAS RETIRED
-- Its content ended at 20260812000000. Everything applied after that — starting
-- with 20260815000000, which fixed two functions that could not run at all —
-- was absent from it. But the file did not know that, and neither did anyone
-- pasting it.
--
-- Pasting it after 20260815000000 had been applied would have re-run
-- CREATE OR REPLACE with the OLD bodies of build_live_exam_report and
-- compute_live_moments, reverting that fix. No error. No warning. The functions
-- still exist, still return JSON, still look healthy — they just answer in an
-- older, broken shape. That is the same failure mode the original header warned
-- about for live_session_sync, turned on the file itself.
--
-- The risk was not theoretical and it grew with every migration. A consolidated
-- file has to be maintained in lockstep with the directory it duplicates, and
-- the moment it falls one migration behind it becomes a device for reverting
-- work, most likely during a rollback, which is exactly when nobody can afford
-- it.
--
-- The original content is in git history if it is ever needed:
--     git log --oneline -- supabase/APPLY_REMAINING.sql
--
-- ============================================================================
-- WHAT TO DO INSTEAD
--
-- Apply the files in supabase/migrations/ directly, in filename order. The
-- timestamps ARE the order. Nothing needs to be consolidated, and a file that
-- is not duplicated cannot fall behind.
--
-- Every statement is idempotent, so re-applying one is safe.
--
-- ORDER IS LOAD-BEARING. CREATE OR REPLACE does not merge function bodies —
-- whichever definition runs LAST is the one the database keeps, and the others
-- are discarded without a word. Six migrations rewrite live_session_sync whole:
--
--     20260802000000  foundations
--     20260803030000  security hardening
--     20260804000000  A3 add time, A10 undo unlock
--     20260808000000  Q15/Q16 show the choices, stage theme
--     20260810000000  Q15b reveal the answer when time is up
--     20260812000000  E3 "off" means off
--     20260820000000  the open question's name tag          [LATEST — must win]
--
-- Run those out of order and the RPC still exists and still looks fine. What
-- you get instead is a projector that has quietly lost a setting, or a
-- mid-question correctness leak reopened, with nothing anywhere saying so.
--
-- ============================================================================
-- THE FULL ORDER, from the point this file used to start
--
--   20260803040000  HOTFIX — a student can SELECT their own participant row
--   20260804000000  A3 add time, A10 undo unlock             [live_session_sync]
--   20260805000000  B14 moments and celebration
--   20260806000000  C7 drag reorder
--   20260807000000  D1 session report
--   20260808000000  Q15 show the choices, Q16 stage theme    [live_session_sync]
--   20260809000000  privacy mode made visible
--   20260810000000  Q15b reveal the answer when time is up   [live_session_sync]
--   20260811000000  A3b end the clock now
--   20260812000000  E3 "off" means off                       [live_session_sync]
--   20260813000000  exam instruction column
--   20260814000000  section navigation mode
--   20260815000000  FIX — window function nesting            ← absent from the
--                     old content of this file; that is why it was retired
--
--   ── Live exams: match translations by name tag, not by seat number ──
--   20260816000000  backfill question_group_id (multi-language exams only)
--   20260817000000  live_primary_questions — the play order, defined once
--   20260818000000  public_profiles view (unrelated; marketplace byline)
--   20260819000000  submit_live_response matches by name tag   [needs ...817]
--   20260820000000  live_session_sync publishes the open tag   [needs ...817]
--   20260821000000  readiness gate on start_live_session
--   20260822000000  reveal timing and timer bounds by play order [needs ...817]
--
-- ============================================================================
-- VERIFYING
--
--   supabase/tests/verify_live_group_ids.sql      data audit, read only
--   supabase/tests/verify_live_group_matching.sql did the migrations land
--   supabase/tests/verify_phase2.sql              36 checks; predates the last
--                                                 several migrations and asserts
--                                                 nothing about them
--
-- Each migration from 20260808000000 onward also ends in its own DO block that
-- raises if its columns, functions or JSON keys did not land — so the paste
-- itself is a check. A half-applied migration stops with an exception at apply
-- time rather than being discovered a week later on a projector in front of a
-- class.
-- ============================================================================
